name: Deploy to Firebase Hosting on Push
'on': push
jobs:
    deploy:
     runs-on: ubuntu-latest
     steps:
      - uses: actions/checkout@v2
      - name: Install Packages
        run: npm install    
      - name: Build App
        run: npm run build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_REACTDEMO_PH }}'
          projectId: firstprojfirebase
          channelId: live
     
      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
       # with:
      #   version: 4.6.1.2450
      #   if: env.SONARCLOUD_SCAN_VARIABLE = '1'
      #   scan: true
               
             
env:
 GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
 SONAR_TOKEN: '${{ secrets.SONAR_TOKEN }}' 
 SONARCLOUD_SCAN_VARIABLE: '${{ secrets.SSONARCLOUD_SCAN_VARIABLE }}' 
